const canvas=document.getElementById('particles'),ctx=canvas.getContext('2d'),glow=document.getElementById('glow'),button=document.getElementById('motion');
const reduced=matchMedia('(prefers-reduced-motion: reduce)');let paused=reduced.matches,w=0,h=0,frame=0,last=0,t=0,points=[];
const pointer={x:0,y:0,vx:0,vy:0,active:false,stamp:0};let trail=[];
function resize(){w=innerWidth;h=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=w*d;canvas.height=h*d;canvas.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);const cols=w<760?66:112,rows=w<760?40:55;points=[];for(let r=0;r<rows;r++)for(let c=0;c<cols;c++)points.push({u:c/(cols-1),v:r/(rows-1),ox:0,oy:0,vx:0,vy:0});draw(0)}
function draw(dt){ctx.clearRect(0,0,w,h);const step=dt*60;for(const p of points){const depth=.55+p.v*.6;let bx=w*.5+(p.u-.5)*w*1.9*depth,by=h*.05+p.v*h*.91+(Math.sin(p.u*9+p.v*5+t*.6)*.6+Math.sin(p.u*15-p.v*7-t*.4)*.22)*h*.13*depth;
if(step){let fx=0,fy=0;for(const q of trail){const dx=bx+p.ox-q.x,dy=by+p.oy-q.y,d2=dx*dx+dy*dy,R=w<760?150:205;if(d2<R*R){const d=Math.sqrt(d2),f=(1-d/R)**2*q.life;fx+=(dx/(d+12)*1.1+q.vx*.075-dy/(d+12)*.65)*f;fy+=(dy/(d+12)*1.1+q.vy*.075+dx/(d+12)*.65)*f}}
p.vx=(p.vx+(fx-p.ox*.018)*step)*Math.pow(.88,step);p.vy=(p.vy+(fy-p.oy*.018)*step)*Math.pow(.88,step);p.ox=Math.max(-130,Math.min(130,p.ox+p.vx*step));p.oy=Math.max(-130,Math.min(130,p.oy+p.vy*step))}
const x=bx+p.ox,y=by+p.oy,energy=Math.min(1,Math.hypot(p.ox,p.oy)/40);const alpha=.18+p.v*.37+energy*.3;ctx.fillStyle=`rgba(${151+Math.floor(energy*50)},${143+Math.floor(energy*55)},250,${alpha})`;ctx.beginPath();ctx.arc(x,y,.65+p.v*.65+energy*.7,0,Math.PI*2);ctx.fill()}}
function animate(now){if(paused||document.hidden)return;const dt=last?Math.min((now-last)/1000,.035):.016;last=now;t+=dt;for(const q of trail)q.life-=dt*1.8;trail=trail.filter(q=>q.life>0);if(pointer.active&&now-pointer.stamp<150){trail.push({x:pointer.x,y:pointer.y,vx:pointer.vx,vy:pointer.vy,life:.6});if(trail.length>9)trail.shift();pointer.vx*=.82;pointer.vy*=.82}draw(dt);frame=requestAnimationFrame(animate)}
function move(x,y){if(paused)return;const now=performance.now(),elapsed=Math.max(8,now-pointer.stamp),continuous=pointer.active&&elapsed<160;pointer.vx=continuous?Math.max(-35,Math.min(35,(x-pointer.x)*16/elapsed)):0;pointer.vy=continuous?Math.max(-35,Math.min(35,(y-pointer.y)*16/elapsed)):0;Object.assign(pointer,{x,y,stamp:now,active:true});trail.push({x,y,vx:pointer.vx,vy:pointer.vy,life:1});if(trail.length>9)trail.shift();glow.style.transform=`translate(${x-210}px,${y-210}px)`}
function release(){pointer.active=false;glow.style.transform='translate(-100%,-100%)'}
function state(){button.textContent=paused?'Resume motion':'Pause motion';button.setAttribute('aria-pressed',String(paused));glow.style.display=paused?'none':'';cancelAnimationFrame(frame);last=0;if(!paused&&!document.hidden)frame=requestAnimationFrame(animate);else draw(0)}
addEventListener('pointermove',e=>{if(e.pointerType!=='touch')move(e.clientX,e.clientY)},{passive:true});addEventListener('pointerdown',e=>move(e.clientX,e.clientY),{passive:true});
// Touch events continue tracking a finger when the browser takes over scrolling.
addEventListener('touchmove',e=>{const touch=e.touches[0];if(touch)move(touch.clientX,touch.clientY)},{passive:true});addEventListener('touchend',release,{passive:true});addEventListener('touchcancel',release,{passive:true});document.addEventListener('pointerleave',release);addEventListener('resize',resize);document.addEventListener('visibilitychange',state);button.addEventListener('click',()=>{paused=!paused;state()});reduced.addEventListener('change',()=>{paused=reduced.matches;state();if(paused)document.querySelectorAll('.reveal').forEach(el=>el.classList.add('visible'))});if(!reduced.matches&&'IntersectionObserver'in window){document.body.classList.add('motion-enabled');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.06});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el))}resize();state();
